from typing import Self

from java.io import ByteArrayInputStream

class Certificate: ...

class CertPath:
    def getEncoded(self, encoding: str) -> bytes: ...

class CertificateFactory:
    @classmethod
    def getInstance(cls, *args: str) -> Self: ...
    def generateCertificate(self, *args: ByteArrayInputStream) -> Certificate: ...
    def generateCertPath(self, *args: list[Certificate]) -> CertPath: ...
